---
- hosts: app_servers
  gather_facts: no
  sudo: no

  tasks:
    - name: restore db
      django_manage: >
        app_path={{ APP_DIR }}
        virtualenv={{ APP_VIRTUALENV }}
        settings=settings.{{ APP_ENVIRONMENT }}
        command=restore-db
