# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefix', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=50)),
                ('client_wsdl', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'network',
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=50)),
                ('sender_id', models.CharField(default='', max_length=50)),
                ('msisdn', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=20)),
                ('state', django_fsm.FSMField(choices=[('received', 'received'), ('started', 'started'), ('failed', 'failed'), ('submitted', 'submitted'), ('completed', 'completed')], default='received', max_length=50, protected=True)),
                ('callback', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Network')),
            ],
            options={
                'db_table': 'sms_message',
            },
        ),
    ]
